# ==== BINDING APPLICATION ====
# These file configures bindings for applications.

# Applications
bind = $mod, K, exec, $term
bind = $mod, f, exec, $browser
bind = $mod, E, exec, $fm
bind = $mod, S, exec, $editor
bind = $mod, SPACE, exec, $menu

# VLX
bind = $mod, T, exec, $vlx-themes switch

# Scripts
bind = $mod, L, exec, $script-power