# ==== BINDING WORKSPACE ====
# These file configures bindings for workspaces.

# Variables
$ws1 = 1
$ws2 = 2
$ws3 = 3
$ws4 = 4

# Switch
bind = $mod CTRL, $right, exec, $hypr-dir/scripts.d/ws-next.sh
bind = $mod CTRL, $left,  exec, $hypr-dir/scripts.d/ws-prev.sh
bind = $mod, 1, workspace, $ws1
bind = $mod, 2, workspace, $ws2
bind = $mod, 3, workspace, $ws3
bind = $mod, 4, workspace, $ws4

# Move
bind = $mod SHIFT, 1, movetoworkspace, $ws1
bind = $mod SHIFT, 2, movetoworkspace, $ws2
bind = $mod SHIFT, 3, movetoworkspace, $ws3
bind = $mod SHIFT, 4, movetoworkspace, $ws4