# ==== BINDING WINDOW ====
# These file configures bindings for windows.

# Floating modifier (mouse)
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
bind = $mod, RETURN, togglefloating

# Window operations
bind = $mod, Q, killactive

# Focus
bind = $mod, $left,  movefocus, l
bind = $mod, $down,  movefocus, d
bind = $mod, $up,    movefocus, u
bind = $mod, $right, movefocus, r

# Move windows
bind = $mod SHIFT, $left,  movewindow, l
bind = $mod SHIFT, $down,  movewindow, d
bind = $mod SHIFT, $up,    movewindow, u
bind = $mod SHIFT, $right, movewindow, r

# Resize mode
bind = $mod, R, submap, resize
submap = resize

binde = , $left,  resizeactive, -50 0
binde = , $down,  resizeactive, 0 50
binde = , $up,    resizeactive, 0 -50
binde = , $right, resizeactive, 50 0

bind = , RETURN, submap, reset
bind = , ESCAPE, submap, reset
bind = $mod, R, submap, reset

submap = reset

# Scratchpad (special workspace)
bind = $mod, minus, movetoworkspacesilent, special:scratchpad
bind = $mod, plus,  togglespecialworkspace, scratchpad