# ==== BINDING SCREENSHOTS ====
# These file configures bindings for screenshots.

bind = , PRINT, submap, screenshot
submap = screenshot

bind = , S, exec, $scns && notify-send "Screenshot" "Full screen"
bind = , F, exec, bash $hypr-dir/scripts.d/scns-focus.sh
bind = , R, exec, $scns -g "$(slurp)" - | swappy -f -

bind = , RETURN, submap, reset
bind = , ESCAPE, submap, reset

submap = reset