# ==== BINDING SCREENSHOTS ====
# This file configures bindings for scrennshots.

bind = $mod, PRINT, submap, screenshot
submap = screenshot

bind = , S, exec, bash -c 'grim'
bind = , F, exec, bash $hypr-dir/scripts.d/scns-focus.sh

bind = , RETURN, submap, reset
bind = , ESCAPE, submap, reset
bind = $mod, PRINT, submap, reset

submap = reset