package templates

import "path/filepath"

func GenerateHypr(data ThemeColorData, cfgDir string) error {
	const tmpl = `# Hyprland theme configuration - generated by vlx-themes

# --- Identity ---
$primary = rgba({{toRgba .Primary}})
$primary_dim = rgba({{toRgba .PrimaryDim}})
$primary_subtle = rgba({{toRgba .PrimarySubtle}})
$primary_muted = rgba({{toRgba .PrimaryMuted}})

$secondary = rgba({{toRgba .Secondary}})
$secondary_dim = rgba({{toRgba .SecondaryDim}})
$secondary_light = rgba({{toRgba .SecondaryLight}})

$accent = rgba({{toRgba .Accent}})
$accent_dim = rgba({{toRgba .AccentDim}})
$accent_light = rgba({{toRgba .AccentLight}})

# --- Backgrounds ---
$base = rgba({{toRgba .Base}})
$mantle = rgba({{toRgba .Mantle}})
$crust = rgba({{toRgba .Crust}})
$surface0 = rgba({{toRgba .Surface0}})
$surface1 = rgba({{toRgba .Surface1}})
$surface2 = rgba({{toRgba .Surface2}})

# --- Foregrounds ---
$text = rgba({{toRgba .Text}})
$subtext = rgba({{toRgba .Subtext}})
$overlay = rgba({{toRgba .Overlay}})
$muted = rgba({{toRgba .Muted}})

# --- Semantic states ---
$success = rgba({{toRgba .Success}})
$warning = rgba({{toRgba .Warning}})
$warning_subtle = rgba({{toRgba .WarningSubtle}})
$error = rgba({{toRgba .Error}})
$error_subtle = rgba({{toRgba .ErrorSubtle}})
$info = rgba({{toRgba .Info}})
$info_subtle = rgba({{toRgba .InfoSubtle}})

# --- On-color ---
$on_primary = rgba({{toRgba .OnPrimary}})
$on_accent = rgba({{toRgba .OnAccent}})
$on_surface = rgba({{toRgba .OnSurface}})

# --- Typography ---
$font_name = {{.FontName}}
$font_name_heading = {{.FontNameHeading}}
$font_name_mono = {{.FontNameMono}}
$font_size = {{.FontSize}}
$font_size_small = {{.FontSizeSmall}}
$font_size_large = {{.FontSizeLarge}}
$font_size_heading = {{.FontSizeHeading}}
`
	return write(filepath.Join(cfgDir, "hypr", "config.d", "40-theme.conf"), tmpl, data)
}
