package templates

import "path/filepath"

func GenerateMako(data ThemeColorData, cfgDir string) error {
	const tmpl = `# Mako theme - generated by vlx-themes

# --- Appearance ---
background-color={{.Surface0}}ee
text-color={{.Text}}
border-color={{.Primary}}dd
progress-color=over {{.Primary}}ee

# --- Fonts ---
font={{.FontName}} {{.FontSize}}

# --- Categories ---
[urgency=low]
border-color={{.Info}}dd
background-color={{.Surface0}}ee

[urgency=normal]
border-color={{.Primary}}dd
background-color={{.Surface0}}ee

[urgency=critical]
border-color={{.Error}}ff
background-color={{.ErrorSubtle}}dd
text-color={{.Error}}
default-timeout=0
`
	return write(filepath.Join(cfgDir, "mako", "theme.conf"), tmpl, data)
}
