package templates

import "path/filepath"

func GenerateRofi(data ThemeColorData, cfgDir string) error {
	const tmpl = `/* Rofi theme - generated by vlx-themes */

* {
    /* Typography */
    font: "{{.FontName}} {{.FontSizeLarge}}";

    /* Backgrounds */
    background: {{.Base}};
    background-alt: {{.Mantle}};
    surface: {{.Surface0}};

    /* Foregrounds */
    foreground: {{.Text}};
    foreground-alt: {{.Subtext}};
    muted: {{.Muted}};

    /* Identity colors */
    primary: {{.Primary}};
    primary-dim: {{.PrimaryDim}};
    primary-subtle: {{.PrimarySubtle}};
    primary-muted: {{.PrimaryMuted}};

    secondary: {{.Secondary}};
    secondary-dim: {{.SecondaryDim}};
    secondary-light: {{.SecondaryLight}};

    accent: {{.Accent}};
    accent-dim: {{.AccentDim}};
    accent-light: {{.AccentLight}};

    /* Semantic states */
    success: {{.Success}};
    warning: {{.Warning}};
    error: {{.Error}};
    info: {{.Info}};

    /* On-color */
    on-primary: {{.OnPrimary}};
    on-accent: {{.OnAccent}};
    on-surface: {{.OnSurface}};
}
`
	return write(filepath.Join(cfgDir, "rofi", "theme.rasi"), tmpl, data)
}
