# ==== GENERAL RULES ====
# This file configures general rules

for_window [title="^Picture-in-picture$"] floating enable
for_window [title=".*Dialog.*"] floating enable
for_window [title="vlx-launcher"] floating enable, focus, border none
for_window [title="vlx-power"] floating enable, focus, border none
for_window [title="vlx-picker"] floating enable, focus, border none

