# ==== PAVUCONTROL WINDOW RULES ====
# Floating window with fixed size, top-right corner

for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] floating enable
for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] resize set 635 400
for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] move position 2805 0
