# ==== PAVUCONTROL WINDOW RULES ====
# Floating window with fixed width and top-left position

for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] floating enable
for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] resize set 635 400
for_window [title=".*(Lautstärkeregler|Volume Control).*" app_id="pavucontrol"] move position 2525 0
