# ==== PAVUCONTROL WINDOW RULES ====
# Floating window with fixed width and top-left position

for_window [title=".*Lautstärkeregler.*"] floating enable
for_window [title=".*Lautstärkeregler.*"] resize set 635 400
for_window [title=".*Lautstärkeregler.*"] move position 2525 0
