# ==== STEAM WINDOW RULES ====
# Floating windows for all dialogs

for_window [title=".*Friends.*"] floating enable
for_window [title=".*Friends.*"] resize set 400 1000
for_window [title=".*Friends.*"] move position 2760 0