# ==== PROTONUP-QT WINDOW RULES ====
# Floating window centered on screen

for_window [title=".*(ProtonUp|pupgui2).*" app_id="net.davidotek.pupgui2"] floating enable
for_window [title=".*(ProtonUp|pupgui2).*" app_id="net.davidotek.pupgui2"] resize set 600 400
for_window [title=".*(ProtonUp|pupgui2).*" app_id="net.davidotek.pupgui2"] move position center
