# ==== BLUETOOTH MANAGER WINDOW RULES ====
# Floating window centered on screen

for_window [title=".*(Bluetooth|Bluetooth Manager).*" app_id="blueman-manager"] floating enable
for_window [title=".*(Bluetooth|Bluetooth Manager).*" app_id="blueman-manager"] resize set 1000 900
for_window [title=".*(Bluetooth|Bluetooth Manager).*" app_id="blueman-manager"] move position center
