# ==== JETBRAINS TOOLBOX WINDOW RULES ====
# Floating window on the top right

for_window [title=".*(JetBrains Toolbox).*" app_id="jetbrains-toolbox"] floating enable
for_window [title=".*(JetBrains Toolbox).*" app_id="jetbrains-toolbox"] move position 2805 0
