# ==== BINDING APPLICATION ====
# These file configures bindings for applications.

# Applications
bindsym $mod+k     exec $term
bindsym $mod+f     exec $browser
bindsym $mod+e     exec $fm
bindsym $mod+s     exec $editor
bindsym $mod+Space exec $menu

# VLX
bindsym $mod+t     exec vlx themes switch

# Scripts
bindsym $mod+l     exec $sh-power