# ==== BINDING APPLICATION ====
# These file configures bindings for applications.

# Applications
bindsym $mod+k exec $term
bindsym $mod+f exec $browser
bindsym $mod+e exec $fm
bindsym $mod+s exec $editor

# Quickshell
bindsym $mod+l exec quickshell ipc call power toggle

# VLX
bindsym $mod+Space exec vlx launcher
bindsym $mod+t exec vlx themes apply
bindsym $mod+b exec vlx bundle install