# ==== BINDING APPLICATION ====
# These file configures bindings for applications.

# Applications
bindsym $mod+k exec $term
bindsym $mod+f exec $browser
bindsym $mod+e exec $fm
bindsym $mod+s exec $editor

# Quickshell
bindsym $mod+l exec quickshell ipc call power toggle
bindsym $kc-cross exec quickshell ipc call commandCenter toggle

# VLX
bindsym $mod+Space exec vlx launcher
bindsym $mod+t exec vlx themes apply
bindsym $mod+m exec vlx mise install
bindsym $mod+m exec vlx bundle install