# ==== BINDING WINDOW ====
# These file configures bindings for windows.

# Floating modifier
floating_modifier $mod normal
bindsym           $mod+Return floating toggle

# Window operations
bindsym $mod+q kill

# Focus
bindsym $mod+$left  focus left
bindsym $mod+$down  focus down
bindsym $mod+$up    focus up
bindsym $mod+$right focus right

# Move windows
bindsym $mod+Shift+$left    move left
bindsym $mod+Shift+$down    move down
bindsym $mod+Shift+$up      move up
bindsym $mod+Shift+$right   move right

# Resize mode
mode "resize" {
    bindsym $left  resize shrink width  25px
    bindsym $down  resize shrink height 25px
    bindsym $up    resize grow   height 25px
    bindsym $right resize grow   width  25px
    
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

# Scratchpad
bindsym $mod+minus  move scratchpad
bindsym $mod+plus   scratchpad show