# ==== BINDING SCREENSHOTS ====
# This file configures bindings for screenshots.

set $screenshot_full grim

mode "screenshot" {
    bindsym s exec $screenshot_full; mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym Print mode "default"
}
bindsym Print mode "screenshot"