# ==== BINDING SCREENSHOTS ====
# These file configures bindings for screenshots.

mode "screenshot" {
    bindsym s exec $scns && notify-send "Screenshot" "Full screen"
    bindsym f exec bash $sway-dir/scripts.d/scns-focus.sh
    bindsym r exec $scns -g "$(slurp)" - | swappy -f -

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym Print mode "screenshot"