blur enable
blur_xray disable

blur_passes 2
blur_radius 8

blur_noise 0.0
blur_brightness 1.0
blur_contrast 1.0
blur_saturation 1.0

corner_radius 10

shadows enable
shadows_on_csd disable

shadow_blur_radius 8
shadow_color #0000007F
shadow_offset 0 0
shadow_inactive_color #0000007F

default_dim_inactive 0.2
dim_inactive_colors.unfocused #00000080
dim_inactive_colors.urgent #FF000080

scratchpad_minimize disable