# ==== GENERAL RULES ====
# This file configures general rules

windowrule=isfloating:1,title:^Picture-in-picture$
windowrule=isfloating:1,title:.*Dialog.*
windowrule=isfloating:1,title:vlx-launcher
windowrule=isfloating:1,title:vlx-power
windowrule=isfloating:1,title:vlx-picker
