# ==== HARDWARE ====
# These file configures hardware.

# Monitors
monitor = DP-2,3440x1440@100,0x0,1.07

# Input
input {
    kb_layout = de
}

# Compatibility
xwayland {
    force_zero_scaling = true
}