# ==== VARIABLES ====
# These file configures most of the variables.

# Modifier keys
$mod = SUPER

# Directories
$hypr-dir   = $XDG_CONFIG_HOME/hypr

# Keychron
$kc-circle   = XF86Tools
$kc-triangle = XF86Launch5
$kc-square   = XF86Launch6
$kc-cross    = XF86Launch7

# Directional keys
$left  = left
$right = right
$up    = up
$down  = down

# Applications
$term     = kitty
$editor   = subl
$fm       = thunar
$browser  = vivaldi
$audio    = pavucontrol
$themes-dir = $XDG_CONFIG_HOME/vlx/themes
$menu     = vlx launcher
$power    = quickshell ipc call power toggle
$cc       = quickshell ipc call commandCenter toggle

# VLX
$vlx-themes = vlx themes