# ==== VARIABLES ====
# These file configures most of the variables.

# Modifier keys
$mod = SUPER

# Directories
$rofi-dir   = $XDG_CONFIG_HOME/rofi
$hypr-dir   = $XDG_CONFIG_HOME/hypr
$waybar-dir = $XDG_CONFIG_HOME/waybar

# Keychron
$kc-circle   = XF86Tools
$kc-triangle = XF86Launch5
$kc-square   = XF86Launch6
$kc-cross    = XF86Launch7

# Directional keys
$left  = left
$right = right
$up    = up
$down  = down

# Applications
$term     = kitty
$menu     = rofi -show drun
$editor   = subl
$fm       = thunar
$browser  = firefox
$audio    = pavucontrol
$scns     = grim

# VLX
$vlx-themes = vlx themes
$vlx-pkg = vlx pkg

# Scripts
$script-power = bash $rofi-dir/scripts.d/select-power.sh