# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Quickshell
exec = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec = systemctl --user start quickshell.service

# Wallpaper
exec = killall hyprpaper; hyprpaper