# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Notifications
exec-once = mako

# Wallpaper
exec = killall hyprpaper; hyprpaper

# Waybar
exec = killall waybar; waybar -c $XDG_CONFIG_HOME/waybar/config-hypr.jsonc