#            _ _                  _                 _
# __   _____| (_)_ __  _   ___  _| | __ _ _ __   __| |
# \ \ / / _ \ | | '_ \| | | \ \/ / |/ _` | '_ \ / _` |
#  \ V /  __/ | | | | | |_| |>  <| | (_| | | | | (_| |
#   \_/ \___|_|_|_| |_|\__,_/_/\_\_|\__,_|_| |_|\__,_|
#                                  Hyprland by rlvelte

ipc = true
splash = false
wallpaper {
    monitor = DP-2
    path = $XDG_CONFIG_HOME/vlx/themes/current.png
    fit_mode = cover
}