# ==== BINDING APPLICATION ====
# This file configures bindings for applications.

# Applications
bind=SUPER,k,spawn,kitty
bind=SUPER,f,spawn,vivaldi
bind=SUPER,e,spawn,thunar
bind=SUPER,s,spawn,subl
bind=SUPER,Space,spawn,vlx launcher
bind=SUPER,l,spawn,quickshell ipc call power toggle

# VLX
bind=SUPER,t,spawn,vlx themes apply

# Keychron
bind=NONE,XF86Launch7,spawn,quickshell ipc call commandCenter toggle
