# ==== BINDING APPLICATION ====
# This file configures bindings for applications.

# Applications
bind=SUPER,k,spawn,kitty
bind=SUPER,f,spawn,firefox
bind=SUPER,e,spawn,thunar
bind=SUPER,s,spawn,subl
bind=SUPER,Space,spawn,quickshell ipc call launcher toggle
bind=SUPER,l,spawn,quickshell ipc call power toggle

# VLX
bind=SUPER,t,spawn,vlx themes apply
