# ==== BINDING TAGS ====
# This file configures bindings for tags (workspaces).

# Persistent tags
tagrule=id:1,no_hide:1,layout_name:tile
tagrule=id:2,no_hide:1,layout_name:tile
tagrule=id:3,no_hide:1,layout_name:tile
tagrule=id:4,no_hide:1,layout_name:tile

# Switch tags via scripts (with boundary check)
bind=SUPER+CTRL,right,spawn_shell,~/.config/mango/scripts.d/ws-next.sh
bind=SUPER+CTRL,left,spawn_shell,~/.config/mango/scripts.d/ws-prev.sh
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4

# Move window to tag
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
