# ==== GENERAL RULES ====
# This file configures general rules

windowrule = float on, match:title ^Picture-in-picture$
windowrule = float on, match:title .*Dialog.*
windowrule = float on, match:title vlx-launcher
windowrule = bordersize 0, match:title vlx-launcher
windowrule = float on, match:title vlx-power
windowrule = bordersize 0, match:title vlx-power
windowrule = float on, match:title vlx-picker
windowrule = bordersize 0, match:title vlx-picker