# ==== STEAM WINDOW RULES ====
# Floating windows for all dialogs

windowrule = float on, match:title .*Friends.*
windowrule = size 400 1290, match:title .*Friends.*
windowrule = move 2820 50, match:title .*Friends.*