# ==== VARIABLES ====
# These file configures most of the variables.

# Modifier keys
set $mod Mod4

# Directories
set $sway-dir   $XDG_CONFIG_HOME/sway
set $themes-dir $XDG_CONFIG_HOME/vlx/themes

# Keychron
set $kc-circle   XF86Tools
set $kc-triangle XF86Launch5
set $kc-square   XF86Launch6
set $kc-cross    XF86Launch7

# Directional keys
set $left  left

set $right right
set $up    up
set $down  down

# Applications
set $term     kitty
set $editor   subl
set $fm       thunar
set $browser  vivaldi
set $audio    pavucontrol
set $menu     quickshell ipc call launcher toggle
set $power    quickshell ipc call power toggle