# ==== VARIABLES ====
# These file configures most of the variables.

# Modifier keys
set $mod Mod4

# Directories
set $rofi-dir   $XDG_CONFIG_HOME/rofi
set $sway-dir   $XDG_CONFIG_HOME/sway
set $waybar-dir $XDG_CONFIG_HOME/waybar
set $themes-dir $XDG_CONFIG_HOME/vlx/themes

# Keychron
set $kc-circle   XF86Tools
set $kc-triangle XF86Launch5
set $kc-square   XF86Launch6
set $kc-cross    XF86Launch7

# Directional keys
set $left  left
set $right right
set $up    up
set $down  down

# Applications
set $term     kitty
set $menu     rofi -show drun
set $editor   subl
set $fm       thunar
set $browser  firefox
set $audio    pavucontrol
set $scns     grim

# Scripts
set $sh-power bash $rofi-dir/scripts.d/select-power.sh