# ==== APPEARANCE ====
# This file configures the styling.

# Window colors
#                       border    background text      indicator  child_border
client.focused          $primary  $surface0  $text     $secondary $primary
client.focused_inactive $surface0 $surface0  $subtext  $surface0  $surface0
client.unfocused        $surface0 $surface0  $subtext  $surface0  $surface0
client.urgent           $error    $surface0  $text     $error     $error
client.placeholder      $surface0 $surface0  $subtext  $surface0  $surface0
client.background       $surface0

# Layout
gaps inner 5
gaps outer 3
default_border pixel 3

# Wallpaper (managed by vlx-theme)
output "*" bg $themes-dir/current.png fill

# Cursor
mouse_warping container
seat seat0 xcursor_theme Adwaita 24
exec export XCURSOR_THEME=Adwaita
exec export XCURSOR_SIZE=24