# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Steam
exec steam

# Quickshell
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK I3SOCK
exec systemctl --user start quickshell.service

# Polkit
exec sh -c 'pgrep -fa "polkit-gnome-authentication-agent-1|polkit.*(authentication|auth)|lxpolkit" >/dev/null 2>&1 || exec /usr/libexec/polkit-gnome-authentication-agent-1'