# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Notifications
exec mako

# Steam
exec steam

# Waybar 
exec_always pkill -x waybar 2>/dev/null; sleep 0.5; waybar -c $waybar-dir/config-sway.jsonc