# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Notifications
exec mako

# Quickshell
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK I3SOCK
exec systemctl --user start quickshell.service