#            _ _                  _                  _ 
# __   _____| (_)_ __  _   ___  _| | _____ _   _  __| |
# \ \ / / _ \ | | '_ \| | | \ \/ / |/ / _ \ | | |/ _` |
#  \ V /  __/ | | | | | |_| |>  <|   <  __/ |_| | (_| |
#   \_/ \___|_|_|_| |_|\__,_/_/\_\_|\_\___|\__, |\__,_|
#                                          |___/       
#                                       KeyD by rlvelte

[ids]
*

[main]
unicode = no

[control+alt]
1 = G-1
2 = G-2
3 = G-3
4 = G-4
5 = G-5
6 = G-6
7 = G-7
8 = G-8
9 = G-9
0 = G-0


- = G--
= = G-=
] = G-]
q = G-q
e = G-e