#            _ _                  _    _ _   _         
# __   _____| (_)_ __  _   ___  _| | _(_) |_| |_ _   _ 
# \ \ / / _ \ | | '_ \| | | \ \/ / |/ / | __| __| | | |
#  \ V /  __/ | | | | | |_| |>  <|   <| | |_| |_| |_| |
#   \_/ \___|_|_|_| |_|\__,_/_/\_\_|\_\_|\__|\__|\__, |
#                                                |___/ 
#                                      Kitty by rlvelte 

font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0
map ctrl+shift+backspace change_font_size all 0

include theme.conf

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

background_opacity 0.7
background_blur 1
remember_window_size  no
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
window_padding_width 0
window_margin_width 2
hide_window_decorations no

enabled_layouts tall
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

scrollback_lines 5000
wheel_scroll_multiplier 3.0

mouse_hide_wait -1

term xterm-kitty
login_shell yes
shell /usr/bin/zsh
enable_audio_bell no