// Quickshell theme — generated by vlx-themes
pragma Singleton
import QtQuick
import Quickshell

Singleton {
    // --- Identity ---
    readonly property color primary: "#30ba78"
    readonly property color primaryDim: "#0e7e3c"
    readonly property color primarySubtle: "#1d8a54"
    readonly property color primaryMuted: "#c4ecda"

    readonly property color secondary: "#0c322c"
    readonly property color secondaryDim: "#0a2924"
    readonly property color secondaryLight: "#1a3d35"

    readonly property color accent: "#fe7c3f"
    readonly property color accentDim: "#bd3314"
    readonly property color accentLight: "#ffb184"

    // --- Backgrounds (darkest -> lightest) ---
    readonly property color base: "#080f0e"
    readonly property color mantle: "#0c1a17"
    readonly property color crust: "#0f2822"
    readonly property color surface0: "#1a3d35"
    readonly property color surface1: "#254d43"
    readonly property color surface2: "#3d6b60"

    // --- Foregrounds ---
    readonly property color text: "#e0f0ee"
    readonly property color subtext: "#a8c8c2"
    readonly property color overlay: "#7daca2"
    readonly property color muted: "#5a8c80"

    // --- Semantic states ---
    readonly property color success: "#30ba78"
    readonly property color warning: "#f0ab00"
    readonly property color warningSubtle: "#ffecb5"
    readonly property color error: "#e85b4a"
    readonly property color errorSubtle: "#fcd4cf"
    readonly property color info: "#00b2e2"
    readonly property color infoSubtle: "#b3e8f6"

    // --- On-color ---
    readonly property color textOnPrimary: "#060f0d"
    readonly property color textOnSecondary: "#e0f0ee"
    readonly property color textOnAccent: "#060f0d"
    readonly property color textOnSurface: "#e0f0ee"

    // --- Typography ---
    readonly property string fontName: "SUSE"
    readonly property string fontNameHeading: "SUSE"
    readonly property string fontNameMono: "JetBrains Mono"
    readonly property int fontSize: 12
    readonly property int fontSizeSmall: 10
    readonly property int fontSizeLarge: 14
    readonly property int fontSizeHeading: 16
}
