# ==== AUTOSTART ====
# This file configures autostart.

# Clipboard
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

# On Init only
exec-once=mako
exec-once=steam

# On Reload
exec=killall swaybg; swaybg -i ~/.config/vlx/themes/current.png
exec=killall waybar; waybar -c ~/.config/waybar/config-mango.jsonc
